### PR TITLE
fav32.png: Switch to grayscale

### PR DESCRIPTION
**Pull request by RichiH**
See https://github.com/grafana/grafana/issues/3615

### CODE REVIEW

**Comment by marefr** [comment]
@RichiH Just noticed this PR been open for a looong time :) We're currently migrating docs to a new solution so will close this. Again, sorry for the late reply

**Comment by RichiH** [comment]
But it was vintage ;)

Seriously though, this is fine as long as I can see which is docs and which
is an instance. Maybe even change then for on-prem and hosted.

Sent by mobile; please excuse my brevity.

**Comment by marefr** [comment]
You have a point. Will forward this to the guy responsible for docs. However need to sync with grafana.com as well so probably more discussion needed around this.

**Comment by RichiH** [comment]
@marefr any update on this?

**Comment by marefr** [comment]
Nope

**Comment by RichiH** [comment]
I would like to stop thinking about this consciously. Can we re-open this so it does not get lost?

**Comment by adeverteuil** [comment]
The new docs site has a different favicon.  
http://staging.docs.grafana.com.s3-website-us-west-2.amazonaws.com/meta/environments/

**Pull request closed without merging**
