### PR TITLE
Chore: Replace systemjs with rollup and upgrade babel

### LINKED ISSUE #159: Add module bundler
We should start using a module bundler so we can start using node modules in our client build.

### PR DESCRIPTION
**Pull request by jschill**
Fixes #159

### CODE REVIEW

**Comment by torkelo** [comment]
Nice! will try to test tomorrow

**Comment by torkelo** [comment]
needs a rebase now that bower PR is merged. 

So I think this is fine as the first step but feels it missing 
* Sass
* babel 
* concat (shim)
* postcss
* hashing output filenames (replace filerev, as filerev has been dead for 5 years)
* uglify + minify 
* serve + livereload 

would be nice to add these rollup plugins so most of the asset pipeline is handled through the same system. But this could be broken up into seperate PRs

**Comment by jschill** [comment]
Yea I thought it would be a good idea to break it up into separate PRs since it's soon vacation season. Great Todo-list though so I'm not missing anything

**Comment by jschill** [comment]
> But this could be broken up into seperate PRs

https://github.com/grafana/grafana.org/issues/197

**Pull request merged**
